#include <stdio.h>
#include <stdlib.h>
#include "LC.h"
#include "WT.h"

int main(int argc, char *argv[]) {
	
	
	/*CGTGT AAGAA CTTCT TTCTA TCTAC CTACA*/
	
	// 5 séquences de 300 bases
	char seq[5][301]={
	"CAGTTAGCCCTAATGCCTCCGGGGTTGTGAAAAGTTTAACCACAATTTGCTGGCTTGGGTTACACCATAGATTTAGACCACTCACCTGATTTTGGGTGAGCGATATGCGTGTGTGTTATGGGAGTAGATTGAATCTCATAGTCTGATACAAGAACTCCCTTCTACATCGCTTGATTTAAGGTTGTTACCCTGACCTGGCATGGCGCGGAGACGAGACGAACTGGGGAGAGATTGTCAAAAGTGAGGGTACGCTGCAGGTAGGTTTTAACATGAGCGAACTTGGACATCTAGACGGGAACG",
	"TTCCACTTGGAGCAACCCGAACACGTGTACAGACATAACTATCGATCTATGCCCGGTATCTGGGGATGGCTCAATGCGCGAGACTACTTTTAAAGCGGCATAACTCTTGAGAAGCTCCTTCTACAGTGCCCGCTGCCTGCGTGCTCCCCACCTGCGCTGCATAGGTCGGCGCATGCGCGCCTATGAGAAACAAGAAAATCGGGTTTCTGTGCAACAGCTTGATTGATGTACGGCCCCTACGCTTATGGAGCATCATCGCGAGCCAAATCAATATCACGGGAATACGATACGGTACGACCA",
	"GCGGCTACGTATTCTGTCGGAGTAGCGGCCGTCTGCCCAGACGACCTATAGAAAGCGGCGGACAGGCTGAGCGAGGTACTACTTCTACAAATACTGTCGATGGTAATCTCCTACCGCACGGCGTCTAAAGCATGGTAAAGAAAATCTCTAGTCTCTGATTCAGCATCTGTGCCGTGTATTAGAACCGTGGGGCCCCCGGAGGTTTCATACCAGTTCGACTATCCGAGATGATCTCCATATCGTCTAATACACTCATCTAGACAGTGCCATAGTGAAAATAGACTAACGGCCCGCCCTTGA",
	"AGCAAGAATTGCCATCCCCCTCTTGCCACACTCACATTATTGGATGTCTACGGACATGATAAATTCGCTCCTATCAATGTACTCCATATGTCTAGACATTATCGGTTGTGAGATTCGGACCCCCACCCGATTGGGTATAGAGAGTATTATATTAGTCGGACTCCGCATTAATATCTCGTGTATAGTGTACCGGTCTATGCGCTTGGGGGGTGATACTCGATTGCGCATTGTTGGAAACTGCCAACTAGAATAGATTTACTTCTACATATTCTGGGCAGCTTGGGGTCTTAGGTCCGAATG",
	"CCTGGGTTGATGTATAATTTTAGTACGGGAGACGTGTGTGTTCGCGCCGCAAGAAGGTCTCTGCAAAAAACCTGTCTCTTCTACACACTGGAAAGTGAAGGGTGAGCGGCGGACATAGGTGTGTCTTGCCTATACGACAGGCGGTTTTGGAACATGCGGCCCCATGTAGCCTGGCCCACAGCCTTTAAAATGGCTTAGCAAAAATGGTACGGCCCTGCCTGAAGTTCGGAGGAGTACCGCCGGGTCGATTTGTGATGTGGTTTCGGGTGTACTTGTGTCAATTGGATTCCGCGAAACCCA"
	};
	char motif[]= "ACACG";
	char valNoeud[6];
	Noeud *racine = nouveauNoeud();
	
	for(int i=0; i<5; i++){
		for (int j=0; j<301-5; j++){
			/*test++;
			printf("%c \n",seq[i][j]);*/
			
			int k=j;
			
			for (int l=0; l < 5 ; l++) {
				valNoeud[l] = seq[i][k];
				//printf("%c", valNoeud[l]);
				k++;
				}
			//printf("\n");

			valNoeud[5] = '\0';
      //printf("Ajout %s\n",valNoeud);
			ajouteMotArbre(racine, valNoeud, i);
			
			}
		}
	
	//int *res = chercheMotArbre2(racine,motif,0);
	//printf("%d \n", res);
	parcoursArbreMot(racine,0);


	return 0;



}

